apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j.fullname" . }}-db-public
spec:
  type: LoadBalancer
  ports:
    - port: 7687
      targetPort: 7687
      name: bolt
    - port: 7474
      targetPort: 7474
      name: http
    - port: 7473
      targetPort: 7473
      name: https
  selector:
    app: {{ include "neo4j.fullname" . }}
